# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-05 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='user_action_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='user_one_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='user_two_id',
            field=models.IntegerField(),
        ),
    ]
