# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-19 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumUserPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_plan_created', models.DateTimeField(auto_now=True)),
                ('user_plan_stopped', models.DateTimeField()),
                ('user_plan_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PremiumUserServicePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_plan_created', models.DateTimeField(auto_now=True)),
                ('service_plan_stopped', models.DateTimeField()),
                ('service_plan_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('service_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_contact_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('service_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_plan_name', models.CharField(max_length=50)),
                ('service_plan_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('user_created', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('user_active', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[(b'ST', b'STUDENT'), (b'PR', b'PROFESSIONAL')], default='PR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_confirmation_id', models.CharField(max_length=100)),
                ('user_confirmed', models.BooleanField(default=False)),
                ('confirmation_completed', models.DateTimeField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevalinks.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_contact_id', models.CharField(max_length=50)),
                ('user_contact_created', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevalinks.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_college', models.CharField(max_length=50)),
                ('user_college_start', models.DateField()),
                ('user_college_end', models.DateField()),
                ('user_college_active', models.BooleanField(default=True)),
                ('user_Description', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevalinks.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to=b'')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevalinks.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_country', models.CharField(max_length=50)),
                ('user_state', models.CharField(choices=[(b'AP', b'Andhra Pradesh'), (b'AR', b'Arunachal Pradesh'), (b'AS', b'Assam'), (b'BR', b'Bihar'), (b'CT', b'Chhattisgarh'), (b'GA', b'Goa'), (b'GJ', b'Gujarat'), (b'HR', b'Haryana'), (b'HP', b'Himachal Pradesh'), (b'JK', b'Jammu and Kashmir'), (b'JH', b'Jharkhand'), (b'KA', b'Karnataka'), (b'KL', b'Kerala'), (b'MP', b'Madhya Pradesh'), (b'MH', b'Maharashtra'), (b'MN', b'Manipur'), (b'ML', b'Meghalaya'), (b'MZ', b'Mizoram'), (b'NL', b'Nagaland'), (b'OR', b'Odisha'), (b'PB', b'Punjab'), (b'RJ', b'Rajasthan'), (b'SK', b'Sikkim'), (b'TN', b'Tamil Nadu'), (b'TG', b'Telangana'), (b'TR', b'Tripura'), (b'UT', b'Uttarakhand'), (b'UP', b'Uttar Pradesh'), (b'WB', b'West Bengal'), (b'AN', b'Andaman and Nicobar Islands'), (b'CH', b'Chandigarh'), (b'DN', b'Dadra and Nagar Haveli'), (b'DD', b'Daman and Diu'), (b'DL', b'Delhi'), (b'LD', b'Lakshadweep'), (b'PY', b'Puducherry')], max_length=50)),
                ('user_district', models.CharField(default='', max_length=50)),
                ('user_city', models.CharField(default='', max_length=50)),
                ('user_area', models.CharField(max_length=50)),
                ('user_postcode', models.CharField(max_length=10)),
                ('user_location_latitude', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('user_location_logitude', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevalinks.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('user_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_plan_name', models.CharField(max_length=50)),
                ('user_plan_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_job_designation', models.CharField(choices=[(b'TRAIN', b'Trainee'), (b'ASSO', b'Associate'), (b'SEN', b'Senior'), (b'LEAD', b'Lead'), (b'AMAN', b'Assistant Manager'), (b'MAN', b'Manager'), (b'SMAN', b'Senior Manager'), (b'ADIR', b'Associate Director'), (b'DIR', b'Director'), (b'SDIR', b'Senior Director'), (b'CHAIR', b'Chairman'), (b'MD', b'Managing Director'), (b'CFO', b'CFO'), (b'CTO', b'CTO'), (b'CEO', b'CEO'), (b'OWN', b'Owner')], max_length=50, null=True)),
                ('user_experience', models.CharField(choices=[(b'U1', b'0 - 1 Year'), (b'U3', b'1 - 3 Year'), (b'U6', b'3 - 6 Year'), (b'U10', b'6 - 10 Year'), (b'U20', b'10 - 20 Year'), (b'A20', b'Above 20 Year')], max_length=50)),
                ('user_industry', models.CharField(choices=[(b'AGRI', b'Agriculture'), (b'BANK', b'Banking'), (b'CONT', b'Construction'), (b'EDU', b'Education'), (b'ENGG', b'Engineering'), (b'FARM', b'Farming'), (b'FOR', b'Forestry'), (b'FIN', b'Finance'), (b'FISH', b'Fishing'), (b'GOV', b'Government Services'), (b'HEAL', b'HealthCare'), (b'INS', b'Insurance'), (b'IT', b'IT'), (b'MDIA', b'Media'), (b'MINE', b'Mining'), (b'NGO', b'NGO'), (b'PHAR', b'Pharmaceuticals'), (b'REAL', b'RealEstate'), (b'SALE', b'Sales'), (b'TRAD', b'Trading'), (b'TRAN', b'Transportation'), (b'OTH', b'Others')], max_length=4, null=True)),
                ('user_profession', models.CharField(max_length=50)),
                ('user_company', models.CharField(max_length=50, null=True)),
                ('user_description', models.TextField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevalinks.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserResetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_id', models.CharField(max_length=100)),
                ('password_reset', models.BooleanField(default=False)),
                ('reset_request', models.DateTimeField(auto_now=True)),
                ('reset_completed', models.DateTimeField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevalinks.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('user_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_title', models.CharField(max_length=50)),
                ('service_Description', models.TextField()),
                ('service_contact', models.IntegerField()),
                ('service_country', models.CharField(max_length=50)),
                ('service_state', models.CharField(max_length=50)),
                ('service_district', models.CharField(max_length=50)),
                ('service_city', models.CharField(max_length=50)),
                ('service_area', models.CharField(max_length=50)),
                ('service_postcode', models.CharField(max_length=10)),
                ('service_created', models.DateTimeField(auto_now=True)),
                ('service_stopped', models.DateTimeField()),
                ('service_active', models.BooleanField()),
                ('service_location_latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('service_location_logitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevalinks.User')),
            ],
        ),
        migrations.AddField(
            model_name='servicecontacts',
            name='service_contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevalinks.UserService'),
        ),
        migrations.AddField(
            model_name='servicecontacts',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevalinks.User'),
        ),
        migrations.AddField(
            model_name='premiumuserserviceplan',
            name='service_plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevalinks.ServicePlan'),
        ),
        migrations.AddField(
            model_name='premiumuserserviceplan',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevalinks.User'),
        ),
        migrations.AddField(
            model_name='premiumuserserviceplan',
            name='user_service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevalinks.UserService'),
        ),
        migrations.AddField(
            model_name='premiumuserplan',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevalinks.User'),
        ),
        migrations.AddField(
            model_name='premiumuserplan',
            name='user_plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevalinks.UserPlan'),
        ),
    ]
