# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-03 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevalinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='werrhfdghdfh', max_length=50),
            preserve_default=False,
        ),
    ]
