# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-23 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevalinks', '0002_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('user_subscription_active', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevalinks.User')),
            ],
        ),
        migrations.RenameModel(
            old_name='UserPlan',
            new_name='Subscription',
        ),
        migrations.RemoveField(
            model_name='premiumuserplan',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='premiumuserplan',
            name='user_plan_id',
        ),
        migrations.RemoveField(
            model_name='premiumuserserviceplan',
            name='service_plan_id',
        ),
        migrations.RemoveField(
            model_name='premiumuserserviceplan',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='premiumuserserviceplan',
            name='user_service_id',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RemoveField(
            model_name='servicecontacts',
            name='service_contact_id',
        ),
        migrations.RemoveField(
            model_name='servicecontacts',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='usercontacts',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userservice',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user_plan_description',
            new_name='subscription_description',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user_plan_id',
            new_name='subscription_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user_plan_name',
            new_name='subscription_name',
        ),
        migrations.DeleteModel(
            name='PremiumUserPlan',
        ),
        migrations.DeleteModel(
            name='PremiumUserServicePlan',
        ),
        migrations.DeleteModel(
            name='ServiceContacts',
        ),
        migrations.DeleteModel(
            name='ServicePlan',
        ),
        migrations.DeleteModel(
            name='UserContacts',
        ),
        migrations.DeleteModel(
            name='UserService',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user_subscription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevalinks.Subscription'),
        ),
    ]
