# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-03 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevalinks', '0003_auto_20170523_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_identifier',
            field=models.CharField(default=b'<function uuid4 at 0x7f0551c1ce60>2017-06-03 17:57:28.814065+00:00', editable=False, max_length=50),
        ),
    ]
