# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-21 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevalinks', '0005_auto_20170603_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField()),
                ('target_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('init_date', models.DateTimeField(auto_now=True)),
                ('ack_date', models.DateTimeField(null=True)),
                ('description_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
            ],
        ),
    ]
