# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-19 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import friends.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sevalinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=friends.utils.get_datetime_now, verbose_name='added')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to='sevalinks.User', verbose_name='from user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='sevalinks.User', verbose_name='to user')),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=friends.utils.get_datetime_now, verbose_name='added')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_unused_', to='sevalinks.User', verbose_name='from user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='sevalinks.User', verbose_name='to user')),
            ],
        ),
        migrations.CreateModel(
            name='FriendshipInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('sent', models.DateTimeField(default=friends.utils.get_datetime_now, verbose_name='sent')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_from', to='sevalinks.User', verbose_name='from user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_to', to='sevalinks.User', verbose_name='to user')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set([('to_user', 'from_user')]),
        ),
    ]
